<!DOCTYPE html>
<html lang="en">
	
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>TOPOCENTRAS.LT - Internetinė parduotuvė</title>
		<meta name="description" content="TOPO CENTRAS - didžiausias buitinės technikos ir elektronikos mažmeninės prekybos tinklas Lietuvoje. Pirkite internetu ir atsiimkite net 37 parduotuvėse!">
		<link rel="icon" href="https://www.topocentras.lt/media/favicon/default/topo.png" type="image/x-icon">
		<!--BOOTSTRAP-->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
		
		
		
		<!--CUSTOM FONTS-->
		<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
		<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
		
		<!--AOS SCROLL-->
		
		<link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
	
		<!--MANO CSS-->
		<link rel="stylesheet" type="text/css" href="style.css">
		
	</head>

	<body>
		<footer style="font-size:13px;    font-family: 'Open Sans'!important; ">
			<div class="container top-menu" >
			  <div class="row" style="margin-left:0px;margin-right:0px; height:33px">
			    <div class="col-2" style="padding-left:0px;padding-right:0px;">
			     
			      <ul class="nav">
					  <li class="nav-item"  >
					    <a class="nav-link active" href="#" style="padding-left:0px; ">Parduotuvės <i class="fas fa-chevron-circle-right"></i></a>
					  </li>
					  <li class="nav-item">
					    <a class="nav-link" href="#">Aplikacija <i class="fas fa-mobile"></i></a>
					  </li>
					</ul>
					
			    </div>
			    <div class="col-8" style="float:right">
			    	
			    	
			    	<ul class="nav">
					  <li class="nav-item">
					    <a class="nav-link active" href="#"><i class="far fa-building"></i> Nemokamas atsiėmimas</a>
					  </li>
					  <li class="nav-item">
					    <a class="nav-link active" href="#" "><i class="fas fa-truck"></i> Pristatymas per 1 - 3 d.d. </a>
					  </li>
					  <li class="nav-item">
					    <a class="nav-link active" href="#""><i class="far fa-money-bill-alt"></i> Atsiskaitymas grynais</a>
					  </li>
					  <li class="nav-item">
					    <a class="nav-link active" href="#"><i class="far fa-calendar-alt"></i> 14 d. grąžinimo garantija</a>
					  </li>
					</ul>
					
			    </div>
			    <div class="col-2" style="padding-right:0px;">
			    	<div style="padding-left: 40px;">
			    	   	<div class="prisijungti" style="float:right; padding-left:10px;">
				    		<a class="nav-link active prisijungti" href="#"><i class="far fa-user" style="margin-right:10px; font-size:15px"></i>Prisijungti</a>
			    	</div>
			    	</div>
			    </div>
			  </div>
			</div>
			<!--BAIGIASI TOP MENU-->
			<br>
			<div class="row top-header">
				<div class="col-2" >
					<img src="https://www.topocentras.lt/skin/frontend/default/v2/img/main-logo2.png"></img>
				</div>
				
				<div class="col-6" >
					<div style="margin-top:20px; margin-left:10px;">
					    <input class="form-control" type="search" placeholder="įveskite ieškomą prekę" aria-label="Search" style="display:inline; max-width:500px; border-radius:0; margin:0px;">
					    <button class="btn btn-outline-success paieskos-mygtukas " type="submit" ><i class="fas fa-search"></i>  Rasti</button>
					</div>
				</div>
				<div class="col-2" style="background:blue">2</div>
				<div class="col-2" style="background:yellow">2</div>
				
			</div>
			
		</footer>
		
		<main></main>
		
		<footer></footer>
		
		<!--BOOTSTRAP JAVASCRIPTS KEEP THEM DOWN-->
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

	</body>
</html>